/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.resources.decisions.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class QueryDecisionsRequestIncludeTraces {
  public static final QueryDecisionsRequestIncludeTraces FALSE = new QueryDecisionsRequestIncludeTraces(Value.FALSE, "false");

  public static final QueryDecisionsRequestIncludeTraces TRUE = new QueryDecisionsRequestIncludeTraces(Value.TRUE, "true");

  private final Value value;

  private final String string;

  QueryDecisionsRequestIncludeTraces(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof QueryDecisionsRequestIncludeTraces && this.string.equals(((QueryDecisionsRequestIncludeTraces) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case FALSE:
        return visitor.visitFalse();
      case TRUE:
        return visitor.visitTrue();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static QueryDecisionsRequestIncludeTraces valueOf(String value) {
    switch (value) {
      case "false":
        return FALSE;
      case "true":
        return TRUE;
      default:
        return new QueryDecisionsRequestIncludeTraces(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    TRUE,

    FALSE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitTrue();

    T visitFalse();

    T visitUnknown(String unknownType);
  }
}
