/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.rulebricks.core.Nullable;
import com.rulebricks.core.NullableNonemptyFilter;
import com.rulebricks.core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ContextBatchResponseResultsItem.Builder.class
)
public final class ContextBatchResponseResultsItem {
  private final Optional<String> instanceId;

  private final Optional<List<Integer>> positions;

  private final Optional<Boolean> isNew;

  private final Optional<ContextBatchResponseResultsItemStatus> status;

  private final Optional<List<String>> have;

  private final Optional<List<String>> need;

  private final Optional<Map<String, Object>> state;

  private final Optional<OffsetDateTime> expiresAt;

  private final Optional<Map<String, Object>> executions;

  private final Optional<List<ContextBatchResponseResultsItemExecutedItem>> executed;

  private final Optional<Boolean> triggered;

  private final Optional<ContextBatchResponseResultsItemReason> reason;

  private final Map<String, Object> additionalProperties;

  private ContextBatchResponseResultsItem(Optional<String> instanceId,
      Optional<List<Integer>> positions, Optional<Boolean> isNew,
      Optional<ContextBatchResponseResultsItemStatus> status, Optional<List<String>> have,
      Optional<List<String>> need, Optional<Map<String, Object>> state,
      Optional<OffsetDateTime> expiresAt, Optional<Map<String, Object>> executions,
      Optional<List<ContextBatchResponseResultsItemExecutedItem>> executed,
      Optional<Boolean> triggered, Optional<ContextBatchResponseResultsItemReason> reason,
      Map<String, Object> additionalProperties) {
    this.instanceId = instanceId;
    this.positions = positions;
    this.isNew = isNew;
    this.status = status;
    this.have = have;
    this.need = need;
    this.state = state;
    this.expiresAt = expiresAt;
    this.executions = executions;
    this.executed = executed;
    this.triggered = triggered;
    this.reason = reason;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("instance_id")
  public Optional<String> getInstanceId() {
    return instanceId;
  }

  /**
   * @return Positions in the submitted array that folded into this instance.
   */
  @JsonProperty("positions")
  public Optional<List<Integer>> getPositions() {
    return positions;
  }

  @JsonProperty("is_new")
  public Optional<Boolean> getIsNew() {
    return isNew;
  }

  @JsonProperty("status")
  public Optional<ContextBatchResponseResultsItemStatus> getStatus() {
    return status;
  }

  @JsonProperty("have")
  public Optional<List<String>> getHave() {
    return have;
  }

  @JsonProperty("need")
  public Optional<List<String>> getNeed() {
    return need;
  }

  /**
   * @return Resolved instance state after merging and any executions, including computed facts.
   */
  @JsonProperty("state")
  public Optional<Map<String, Object>> getState() {
    return state;
  }

  @JsonIgnore
  public Optional<OffsetDateTime> getExpiresAt() {
    if (expiresAt == null) {
      return Optional.empty();
    }
    return expiresAt;
  }

  /**
   * @return Per-asset record of the last run: input hash, status, timestamp, trace IDs, error.
   */
  @JsonProperty("executions")
  public Optional<Map<String, Object>> getExecutions() {
    return executions;
  }

  /**
   * @return Assets evaluated for this instance in this request.
   */
  @JsonProperty("executed")
  public Optional<List<ContextBatchResponseResultsItemExecutedItem>> getExecuted() {
    return executed;
  }

  /**
   * @return True when at least one bound asset was considered for this instance - including assets that settled as skipped_already_run. False (with a reason) when nothing was attempted.
   */
  @JsonProperty("triggered")
  public Optional<Boolean> getTriggered() {
    return triggered;
  }

  /**
   * @return Present when triggered is false (executed is empty): not_ready = required facts still missing; inputs_unchanged = the instance is complete but no bound asset had satisfiable inputs to attempt; no_bound_assets = the context has no published bound rules or flows; auto_execute_disabled = the context's auto_execute_decisions is off; execution_unavailable = the execution backend was unreachable. Note: assets whose inputs are unchanged since their last successful run appear as executed entries with status skipped_already_run and leave triggered true.
   */
  @JsonProperty("reason")
  public Optional<ContextBatchResponseResultsItemReason> getReason() {
    return reason;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("expires_at")
  private Optional<OffsetDateTime> _getExpiresAt() {
    return expiresAt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ContextBatchResponseResultsItem && equalTo((ContextBatchResponseResultsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ContextBatchResponseResultsItem other) {
    return instanceId.equals(other.instanceId) && positions.equals(other.positions) && isNew.equals(other.isNew) && status.equals(other.status) && have.equals(other.have) && need.equals(other.need) && state.equals(other.state) && expiresAt.equals(other.expiresAt) && executions.equals(other.executions) && executed.equals(other.executed) && triggered.equals(other.triggered) && reason.equals(other.reason);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.instanceId, this.positions, this.isNew, this.status, this.have, this.need, this.state, this.expiresAt, this.executions, this.executed, this.triggered, this.reason);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> instanceId = Optional.empty();

    private Optional<List<Integer>> positions = Optional.empty();

    private Optional<Boolean> isNew = Optional.empty();

    private Optional<ContextBatchResponseResultsItemStatus> status = Optional.empty();

    private Optional<List<String>> have = Optional.empty();

    private Optional<List<String>> need = Optional.empty();

    private Optional<Map<String, Object>> state = Optional.empty();

    private Optional<OffsetDateTime> expiresAt = Optional.empty();

    private Optional<Map<String, Object>> executions = Optional.empty();

    private Optional<List<ContextBatchResponseResultsItemExecutedItem>> executed = Optional.empty();

    private Optional<Boolean> triggered = Optional.empty();

    private Optional<ContextBatchResponseResultsItemReason> reason = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ContextBatchResponseResultsItem other) {
      instanceId(other.getInstanceId());
      positions(other.getPositions());
      isNew(other.getIsNew());
      status(other.getStatus());
      have(other.getHave());
      need(other.getNeed());
      state(other.getState());
      expiresAt(other.getExpiresAt());
      executions(other.getExecutions());
      executed(other.getExecuted());
      triggered(other.getTriggered());
      reason(other.getReason());
      return this;
    }

    @JsonSetter(
        value = "instance_id",
        nulls = Nulls.SKIP
    )
    public Builder instanceId(Optional<String> instanceId) {
      this.instanceId = instanceId;
      return this;
    }

    public Builder instanceId(String instanceId) {
      this.instanceId = Optional.ofNullable(instanceId);
      return this;
    }

    /**
     * <p>Positions in the submitted array that folded into this instance.</p>
     */
    @JsonSetter(
        value = "positions",
        nulls = Nulls.SKIP
    )
    public Builder positions(Optional<List<Integer>> positions) {
      this.positions = positions;
      return this;
    }

    public Builder positions(List<Integer> positions) {
      this.positions = Optional.ofNullable(positions);
      return this;
    }

    @JsonSetter(
        value = "is_new",
        nulls = Nulls.SKIP
    )
    public Builder isNew(Optional<Boolean> isNew) {
      this.isNew = isNew;
      return this;
    }

    public Builder isNew(Boolean isNew) {
      this.isNew = Optional.ofNullable(isNew);
      return this;
    }

    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public Builder status(Optional<ContextBatchResponseResultsItemStatus> status) {
      this.status = status;
      return this;
    }

    public Builder status(ContextBatchResponseResultsItemStatus status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    @JsonSetter(
        value = "have",
        nulls = Nulls.SKIP
    )
    public Builder have(Optional<List<String>> have) {
      this.have = have;
      return this;
    }

    public Builder have(List<String> have) {
      this.have = Optional.ofNullable(have);
      return this;
    }

    @JsonSetter(
        value = "need",
        nulls = Nulls.SKIP
    )
    public Builder need(Optional<List<String>> need) {
      this.need = need;
      return this;
    }

    public Builder need(List<String> need) {
      this.need = Optional.ofNullable(need);
      return this;
    }

    /**
     * <p>Resolved instance state after merging and any executions, including computed facts.</p>
     */
    @JsonSetter(
        value = "state",
        nulls = Nulls.SKIP
    )
    public Builder state(Optional<Map<String, Object>> state) {
      this.state = state;
      return this;
    }

    public Builder state(Map<String, Object> state) {
      this.state = Optional.ofNullable(state);
      return this;
    }

    @JsonSetter(
        value = "expires_at",
        nulls = Nulls.SKIP
    )
    public Builder expiresAt(Optional<OffsetDateTime> expiresAt) {
      this.expiresAt = expiresAt;
      return this;
    }

    public Builder expiresAt(OffsetDateTime expiresAt) {
      this.expiresAt = Optional.ofNullable(expiresAt);
      return this;
    }

    public Builder expiresAt(Nullable<OffsetDateTime> expiresAt) {
      if (expiresAt.isNull()) {
        this.expiresAt = null;
      }
      else if (expiresAt.isEmpty()) {
        this.expiresAt = Optional.empty();
      }
      else {
        this.expiresAt = Optional.of(expiresAt.get());
      }
      return this;
    }

    /**
     * <p>Per-asset record of the last run: input hash, status, timestamp, trace IDs, error.</p>
     */
    @JsonSetter(
        value = "executions",
        nulls = Nulls.SKIP
    )
    public Builder executions(Optional<Map<String, Object>> executions) {
      this.executions = executions;
      return this;
    }

    public Builder executions(Map<String, Object> executions) {
      this.executions = Optional.ofNullable(executions);
      return this;
    }

    /**
     * <p>Assets evaluated for this instance in this request.</p>
     */
    @JsonSetter(
        value = "executed",
        nulls = Nulls.SKIP
    )
    public Builder executed(Optional<List<ContextBatchResponseResultsItemExecutedItem>> executed) {
      this.executed = executed;
      return this;
    }

    public Builder executed(List<ContextBatchResponseResultsItemExecutedItem> executed) {
      this.executed = Optional.ofNullable(executed);
      return this;
    }

    /**
     * <p>True when at least one bound asset was considered for this instance - including assets that settled as skipped_already_run. False (with a reason) when nothing was attempted.</p>
     */
    @JsonSetter(
        value = "triggered",
        nulls = Nulls.SKIP
    )
    public Builder triggered(Optional<Boolean> triggered) {
      this.triggered = triggered;
      return this;
    }

    public Builder triggered(Boolean triggered) {
      this.triggered = Optional.ofNullable(triggered);
      return this;
    }

    /**
     * <p>Present when triggered is false (executed is empty): not_ready = required facts still missing; inputs_unchanged = the instance is complete but no bound asset had satisfiable inputs to attempt; no_bound_assets = the context has no published bound rules or flows; auto_execute_disabled = the context's auto_execute_decisions is off; execution_unavailable = the execution backend was unreachable. Note: assets whose inputs are unchanged since their last successful run appear as executed entries with status skipped_already_run and leave triggered true.</p>
     */
    @JsonSetter(
        value = "reason",
        nulls = Nulls.SKIP
    )
    public Builder reason(Optional<ContextBatchResponseResultsItemReason> reason) {
      this.reason = reason;
      return this;
    }

    public Builder reason(ContextBatchResponseResultsItemReason reason) {
      this.reason = Optional.ofNullable(reason);
      return this;
    }

    public ContextBatchResponseResultsItem build() {
      return new ContextBatchResponseResultsItem(instanceId, positions, isNew, status, have, need, state, expiresAt, executions, executed, triggered, reason, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
