/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.rulebricks.core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ContextBatchResponseRejectionsItem.Builder.class
)
public final class ContextBatchResponseRejectionsItem {
  private final Optional<Integer> position;

  private final Optional<String> error;

  private final Map<String, Object> additionalProperties;

  private ContextBatchResponseRejectionsItem(Optional<Integer> position, Optional<String> error,
      Map<String, Object> additionalProperties) {
    this.position = position;
    this.error = error;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("position")
  public Optional<Integer> getPosition() {
    return position;
  }

  @JsonProperty("error")
  public Optional<String> getError() {
    return error;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ContextBatchResponseRejectionsItem && equalTo((ContextBatchResponseRejectionsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ContextBatchResponseRejectionsItem other) {
    return position.equals(other.position) && error.equals(other.error);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.position, this.error);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Integer> position = Optional.empty();

    private Optional<String> error = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ContextBatchResponseRejectionsItem other) {
      position(other.getPosition());
      error(other.getError());
      return this;
    }

    @JsonSetter(
        value = "position",
        nulls = Nulls.SKIP
    )
    public Builder position(Optional<Integer> position) {
      this.position = position;
      return this;
    }

    public Builder position(Integer position) {
      this.position = Optional.ofNullable(position);
      return this;
    }

    @JsonSetter(
        value = "error",
        nulls = Nulls.SKIP
    )
    public Builder error(Optional<String> error) {
      this.error = error;
      return this;
    }

    public Builder error(String error) {
      this.error = Optional.ofNullable(error);
      return this;
    }

    public ContextBatchResponseRejectionsItem build() {
      return new ContextBatchResponseRejectionsItem(position, error, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
