/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.rulebricks.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ContextRelationshipOutgoing.Builder.class
)
public final class ContextRelationshipOutgoing implements IContextRelationshipBase {
  private final Optional<String> id;

  private final Optional<ContextRelationshipBaseRelationType> relationType;

  private final Optional<String> foreignKeyFact;

  private final Optional<String> name;

  private final Optional<String> description;

  private final Optional<OffsetDateTime> createdAt;

  private final Optional<ContextRelationshipOutgoingTargetContext> targetContext;

  private final Map<String, Object> additionalProperties;

  private ContextRelationshipOutgoing(Optional<String> id,
      Optional<ContextRelationshipBaseRelationType> relationType, Optional<String> foreignKeyFact,
      Optional<String> name, Optional<String> description, Optional<OffsetDateTime> createdAt,
      Optional<ContextRelationshipOutgoingTargetContext> targetContext,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.relationType = relationType;
    this.foreignKeyFact = foreignKeyFact;
    this.name = name;
    this.description = description;
    this.createdAt = createdAt;
    this.targetContext = targetContext;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The unique identifier for the relationship.
   */
  @JsonProperty("id")
  @java.lang.Override
  public Optional<String> getId() {
    return id;
  }

  /**
   * @return The type of relationship.
   */
  @JsonProperty("relation_type")
  public Optional<ContextRelationshipBaseRelationType> getRelationType() {
    return relationType;
  }

  /**
   * @return The field key used as the foreign key.
   */
  @JsonProperty("foreign_key_fact")
  @java.lang.Override
  public Optional<String> getForeignKeyFact() {
    return foreignKeyFact;
  }

  /**
   * @return Runtime relationship key used by derived expressions. It is normalized to lowercase snake_case.
   */
  @JsonProperty("name")
  @java.lang.Override
  public Optional<String> getName() {
    return name;
  }

  /**
   * @return Description of the relationship.
   */
  @JsonProperty("description")
  @java.lang.Override
  public Optional<String> getDescription() {
    return description;
  }

  /**
   * @return When the relationship was created.
   */
  @JsonProperty("created_at")
  @java.lang.Override
  public Optional<OffsetDateTime> getCreatedAt() {
    return createdAt;
  }

  @JsonProperty("target_context")
  public Optional<ContextRelationshipOutgoingTargetContext> getTargetContext() {
    return targetContext;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ContextRelationshipOutgoing && equalTo((ContextRelationshipOutgoing) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ContextRelationshipOutgoing other) {
    return id.equals(other.id) && relationType.equals(other.relationType) && foreignKeyFact.equals(other.foreignKeyFact) && name.equals(other.name) && description.equals(other.description) && createdAt.equals(other.createdAt) && targetContext.equals(other.targetContext);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.relationType, this.foreignKeyFact, this.name, this.description, this.createdAt, this.targetContext);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> id = Optional.empty();

    private Optional<ContextRelationshipBaseRelationType> relationType = Optional.empty();

    private Optional<String> foreignKeyFact = Optional.empty();

    private Optional<String> name = Optional.empty();

    private Optional<String> description = Optional.empty();

    private Optional<OffsetDateTime> createdAt = Optional.empty();

    private Optional<ContextRelationshipOutgoingTargetContext> targetContext = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ContextRelationshipOutgoing other) {
      id(other.getId());
      relationType(other.getRelationType());
      foreignKeyFact(other.getForeignKeyFact());
      name(other.getName());
      description(other.getDescription());
      createdAt(other.getCreatedAt());
      targetContext(other.getTargetContext());
      return this;
    }

    /**
     * <p>The unique identifier for the relationship.</p>
     */
    @JsonSetter(
        value = "id",
        nulls = Nulls.SKIP
    )
    public Builder id(Optional<String> id) {
      this.id = id;
      return this;
    }

    public Builder id(String id) {
      this.id = Optional.ofNullable(id);
      return this;
    }

    /**
     * <p>The type of relationship.</p>
     */
    @JsonSetter(
        value = "relation_type",
        nulls = Nulls.SKIP
    )
    public Builder relationType(Optional<ContextRelationshipBaseRelationType> relationType) {
      this.relationType = relationType;
      return this;
    }

    public Builder relationType(ContextRelationshipBaseRelationType relationType) {
      this.relationType = Optional.ofNullable(relationType);
      return this;
    }

    /**
     * <p>The field key used as the foreign key.</p>
     */
    @JsonSetter(
        value = "foreign_key_fact",
        nulls = Nulls.SKIP
    )
    public Builder foreignKeyFact(Optional<String> foreignKeyFact) {
      this.foreignKeyFact = foreignKeyFact;
      return this;
    }

    public Builder foreignKeyFact(String foreignKeyFact) {
      this.foreignKeyFact = Optional.ofNullable(foreignKeyFact);
      return this;
    }

    /**
     * <p>Runtime relationship key used by derived expressions. It is normalized to lowercase snake_case.</p>
     */
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public Builder name(Optional<String> name) {
      this.name = name;
      return this;
    }

    public Builder name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    /**
     * <p>Description of the relationship.</p>
     */
    @JsonSetter(
        value = "description",
        nulls = Nulls.SKIP
    )
    public Builder description(Optional<String> description) {
      this.description = description;
      return this;
    }

    public Builder description(String description) {
      this.description = Optional.ofNullable(description);
      return this;
    }

    /**
     * <p>When the relationship was created.</p>
     */
    @JsonSetter(
        value = "created_at",
        nulls = Nulls.SKIP
    )
    public Builder createdAt(Optional<OffsetDateTime> createdAt) {
      this.createdAt = createdAt;
      return this;
    }

    public Builder createdAt(OffsetDateTime createdAt) {
      this.createdAt = Optional.ofNullable(createdAt);
      return this;
    }

    @JsonSetter(
        value = "target_context",
        nulls = Nulls.SKIP
    )
    public Builder targetContext(Optional<ContextRelationshipOutgoingTargetContext> targetContext) {
      this.targetContext = targetContext;
      return this;
    }

    public Builder targetContext(ContextRelationshipOutgoingTargetContext targetContext) {
      this.targetContext = Optional.ofNullable(targetContext);
      return this;
    }

    public ContextRelationshipOutgoing build() {
      return new ContextRelationshipOutgoing(id, relationType, foreignKeyFact, name, description, createdAt, targetContext, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
