/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ContextBatchResponseResultsItemReason {
  public static final ContextBatchResponseResultsItemReason INPUTS_UNCHANGED = new ContextBatchResponseResultsItemReason(Value.INPUTS_UNCHANGED, "inputs_unchanged");

  public static final ContextBatchResponseResultsItemReason NO_BOUND_ASSETS = new ContextBatchResponseResultsItemReason(Value.NO_BOUND_ASSETS, "no_bound_assets");

  public static final ContextBatchResponseResultsItemReason NOT_READY = new ContextBatchResponseResultsItemReason(Value.NOT_READY, "not_ready");

  public static final ContextBatchResponseResultsItemReason AUTO_EXECUTE_DISABLED = new ContextBatchResponseResultsItemReason(Value.AUTO_EXECUTE_DISABLED, "auto_execute_disabled");

  public static final ContextBatchResponseResultsItemReason EXECUTION_UNAVAILABLE = new ContextBatchResponseResultsItemReason(Value.EXECUTION_UNAVAILABLE, "execution_unavailable");

  private final Value value;

  private final String string;

  ContextBatchResponseResultsItemReason(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ContextBatchResponseResultsItemReason && this.string.equals(((ContextBatchResponseResultsItemReason) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case INPUTS_UNCHANGED:
        return visitor.visitInputsUnchanged();
      case NO_BOUND_ASSETS:
        return visitor.visitNoBoundAssets();
      case NOT_READY:
        return visitor.visitNotReady();
      case AUTO_EXECUTE_DISABLED:
        return visitor.visitAutoExecuteDisabled();
      case EXECUTION_UNAVAILABLE:
        return visitor.visitExecutionUnavailable();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ContextBatchResponseResultsItemReason valueOf(String value) {
    switch (value) {
      case "inputs_unchanged":
        return INPUTS_UNCHANGED;
      case "no_bound_assets":
        return NO_BOUND_ASSETS;
      case "not_ready":
        return NOT_READY;
      case "auto_execute_disabled":
        return AUTO_EXECUTE_DISABLED;
      case "execution_unavailable":
        return EXECUTION_UNAVAILABLE;
      default:
        return new ContextBatchResponseResultsItemReason(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    NOT_READY,

    INPUTS_UNCHANGED,

    NO_BOUND_ASSETS,

    AUTO_EXECUTE_DISABLED,

    EXECUTION_UNAVAILABLE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitNotReady();

    T visitInputsUnchanged();

    T visitNoBoundAssets();

    T visitAutoExecuteDisabled();

    T visitExecutionUnavailable();

    T visitUnknown(String unknownType);
  }
}
