/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ContextBaseOnSchemaMismatch {
  public static final ContextBaseOnSchemaMismatch REJECT = new ContextBaseOnSchemaMismatch(Value.REJECT, "reject");

  public static final ContextBaseOnSchemaMismatch IGNORE = new ContextBaseOnSchemaMismatch(Value.IGNORE, "ignore");

  public static final ContextBaseOnSchemaMismatch STORE = new ContextBaseOnSchemaMismatch(Value.STORE, "store");

  private final Value value;

  private final String string;

  ContextBaseOnSchemaMismatch(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ContextBaseOnSchemaMismatch && this.string.equals(((ContextBaseOnSchemaMismatch) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case REJECT:
        return visitor.visitReject();
      case IGNORE:
        return visitor.visitIgnore();
      case STORE:
        return visitor.visitStore();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ContextBaseOnSchemaMismatch valueOf(String value) {
    switch (value) {
      case "reject":
        return REJECT;
      case "ignore":
        return IGNORE;
      case "store":
        return STORE;
      default:
        return new ContextBaseOnSchemaMismatch(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    IGNORE,

    REJECT,

    STORE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitIgnore();

    T visitReject();

    T visitStore();

    T visitUnknown(String unknownType);
  }
}
