/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.rulebricks.core.Nullable;
import com.rulebricks.core.NullableNonemptyFilter;
import com.rulebricks.core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = FlowDetail.Builder.class
)
public final class FlowDetail implements IFlowBase {
  private final Optional<String> id;

  private final Optional<String> name;

  private final Optional<String> description;

  private final Optional<String> slug;

  private final Optional<Boolean> published;

  private final Optional<OffsetDateTime> updatedAt;

  private final Optional<FlowDetailOriginRule> originRule;

  private final Optional<FlowDetailContext> context;

  private final Optional<List<String>> userGroups;

  private final Optional<Folder> folder;

  private final Map<String, Object> additionalProperties;

  private FlowDetail(Optional<String> id, Optional<String> name, Optional<String> description,
      Optional<String> slug, Optional<Boolean> published, Optional<OffsetDateTime> updatedAt,
      Optional<FlowDetailOriginRule> originRule, Optional<FlowDetailContext> context,
      Optional<List<String>> userGroups, Optional<Folder> folder,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.name = name;
    this.description = description;
    this.slug = slug;
    this.published = published;
    this.updatedAt = updatedAt;
    this.originRule = originRule;
    this.context = context;
    this.userGroups = userGroups;
    this.folder = folder;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The unique identifier for the flow.
   */
  @JsonProperty("id")
  @java.lang.Override
  public Optional<String> getId() {
    return id;
  }

  /**
   * @return The name of the flow.
   */
  @JsonProperty("name")
  @java.lang.Override
  public Optional<String> getName() {
    return name;
  }

  /**
   * @return The description of the flow.
   */
  @JsonProperty("description")
  @java.lang.Override
  public Optional<String> getDescription() {
    return description;
  }

  /**
   * @return The unique slug for the flow used in API requests.
   */
  @JsonProperty("slug")
  @java.lang.Override
  public Optional<String> getSlug() {
    return slug;
  }

  /**
   * @return Whether the flow is published.
   */
  @JsonProperty("published")
  public Optional<Boolean> getPublished() {
    return published;
  }

  /**
   * @return The date this flow was last updated.
   */
  @JsonProperty("updated_at")
  public Optional<OffsetDateTime> getUpdatedAt() {
    return updatedAt;
  }

  /**
   * @return The origin rule that this flow starts from. Flows execute starting from this rule's outputs.
   */
  @JsonIgnore
  public Optional<FlowDetailOriginRule> getOriginRule() {
    if (originRule == null) {
      return Optional.empty();
    }
    return originRule;
  }

  /**
   * @return The context this flow is bound to (via its origin rule). Flows inherit context binding from their origin rule.
   */
  @JsonIgnore
  public Optional<FlowDetailContext> getContext() {
    if (context == null) {
      return Optional.empty();
    }
    return context;
  }

  /**
   * @return The user groups this flow is assigned to.
   */
  @JsonProperty("user_groups")
  public Optional<List<String>> getUserGroups() {
    return userGroups;
  }

  /**
   * @return The folder this flow belongs to, if any.
   */
  @JsonIgnore
  public Optional<Folder> getFolder() {
    if (folder == null) {
      return Optional.empty();
    }
    return folder;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("origin_rule")
  private Optional<FlowDetailOriginRule> _getOriginRule() {
    return originRule;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("context")
  private Optional<FlowDetailContext> _getContext() {
    return context;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("folder")
  private Optional<Folder> _getFolder() {
    return folder;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof FlowDetail && equalTo((FlowDetail) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(FlowDetail other) {
    return id.equals(other.id) && name.equals(other.name) && description.equals(other.description) && slug.equals(other.slug) && published.equals(other.published) && updatedAt.equals(other.updatedAt) && originRule.equals(other.originRule) && context.equals(other.context) && userGroups.equals(other.userGroups) && folder.equals(other.folder);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.name, this.description, this.slug, this.published, this.updatedAt, this.originRule, this.context, this.userGroups, this.folder);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> id = Optional.empty();

    private Optional<String> name = Optional.empty();

    private Optional<String> description = Optional.empty();

    private Optional<String> slug = Optional.empty();

    private Optional<Boolean> published = Optional.empty();

    private Optional<OffsetDateTime> updatedAt = Optional.empty();

    private Optional<FlowDetailOriginRule> originRule = Optional.empty();

    private Optional<FlowDetailContext> context = Optional.empty();

    private Optional<List<String>> userGroups = Optional.empty();

    private Optional<Folder> folder = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(FlowDetail other) {
      id(other.getId());
      name(other.getName());
      description(other.getDescription());
      slug(other.getSlug());
      published(other.getPublished());
      updatedAt(other.getUpdatedAt());
      originRule(other.getOriginRule());
      context(other.getContext());
      userGroups(other.getUserGroups());
      folder(other.getFolder());
      return this;
    }

    /**
     * <p>The unique identifier for the flow.</p>
     */
    @JsonSetter(
        value = "id",
        nulls = Nulls.SKIP
    )
    public Builder id(Optional<String> id) {
      this.id = id;
      return this;
    }

    public Builder id(String id) {
      this.id = Optional.ofNullable(id);
      return this;
    }

    /**
     * <p>The name of the flow.</p>
     */
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public Builder name(Optional<String> name) {
      this.name = name;
      return this;
    }

    public Builder name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    /**
     * <p>The description of the flow.</p>
     */
    @JsonSetter(
        value = "description",
        nulls = Nulls.SKIP
    )
    public Builder description(Optional<String> description) {
      this.description = description;
      return this;
    }

    public Builder description(String description) {
      this.description = Optional.ofNullable(description);
      return this;
    }

    /**
     * <p>The unique slug for the flow used in API requests.</p>
     */
    @JsonSetter(
        value = "slug",
        nulls = Nulls.SKIP
    )
    public Builder slug(Optional<String> slug) {
      this.slug = slug;
      return this;
    }

    public Builder slug(String slug) {
      this.slug = Optional.ofNullable(slug);
      return this;
    }

    /**
     * <p>Whether the flow is published.</p>
     */
    @JsonSetter(
        value = "published",
        nulls = Nulls.SKIP
    )
    public Builder published(Optional<Boolean> published) {
      this.published = published;
      return this;
    }

    public Builder published(Boolean published) {
      this.published = Optional.ofNullable(published);
      return this;
    }

    /**
     * <p>The date this flow was last updated.</p>
     */
    @JsonSetter(
        value = "updated_at",
        nulls = Nulls.SKIP
    )
    public Builder updatedAt(Optional<OffsetDateTime> updatedAt) {
      this.updatedAt = updatedAt;
      return this;
    }

    public Builder updatedAt(OffsetDateTime updatedAt) {
      this.updatedAt = Optional.ofNullable(updatedAt);
      return this;
    }

    /**
     * <p>The origin rule that this flow starts from. Flows execute starting from this rule's outputs.</p>
     */
    @JsonSetter(
        value = "origin_rule",
        nulls = Nulls.SKIP
    )
    public Builder originRule(Optional<FlowDetailOriginRule> originRule) {
      this.originRule = originRule;
      return this;
    }

    public Builder originRule(FlowDetailOriginRule originRule) {
      this.originRule = Optional.ofNullable(originRule);
      return this;
    }

    public Builder originRule(Nullable<FlowDetailOriginRule> originRule) {
      if (originRule.isNull()) {
        this.originRule = null;
      }
      else if (originRule.isEmpty()) {
        this.originRule = Optional.empty();
      }
      else {
        this.originRule = Optional.of(originRule.get());
      }
      return this;
    }

    /**
     * <p>The context this flow is bound to (via its origin rule). Flows inherit context binding from their origin rule.</p>
     */
    @JsonSetter(
        value = "context",
        nulls = Nulls.SKIP
    )
    public Builder context(Optional<FlowDetailContext> context) {
      this.context = context;
      return this;
    }

    public Builder context(FlowDetailContext context) {
      this.context = Optional.ofNullable(context);
      return this;
    }

    public Builder context(Nullable<FlowDetailContext> context) {
      if (context.isNull()) {
        this.context = null;
      }
      else if (context.isEmpty()) {
        this.context = Optional.empty();
      }
      else {
        this.context = Optional.of(context.get());
      }
      return this;
    }

    /**
     * <p>The user groups this flow is assigned to.</p>
     */
    @JsonSetter(
        value = "user_groups",
        nulls = Nulls.SKIP
    )
    public Builder userGroups(Optional<List<String>> userGroups) {
      this.userGroups = userGroups;
      return this;
    }

    public Builder userGroups(List<String> userGroups) {
      this.userGroups = Optional.ofNullable(userGroups);
      return this;
    }

    /**
     * <p>The folder this flow belongs to, if any.</p>
     */
    @JsonSetter(
        value = "folder",
        nulls = Nulls.SKIP
    )
    public Builder folder(Optional<Folder> folder) {
      this.folder = folder;
      return this;
    }

    public Builder folder(Folder folder) {
      this.folder = Optional.ofNullable(folder);
      return this;
    }

    public Builder folder(Nullable<Folder> folder) {
      if (folder.isNull()) {
        this.folder = null;
      }
      else if (folder.isEmpty()) {
        this.folder = Optional.empty();
      }
      else {
        this.folder = Optional.of(folder.get());
      }
      return this;
    }

    public FlowDetail build() {
      return new FlowDetail(id, name, description, slug, published, updatedAt, originRule, context, userGroups, folder, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
