/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.rulebricks.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = RulebricksFlowNodeOutputsItem.Builder.class
)
public final class RulebricksFlowNodeOutputsItem {
  private final String key;

  private final Optional<RulebricksFlowNodeOutputsItemType> type;

  private final Optional<String> name;

  private final Map<String, Object> additionalProperties;

  private RulebricksFlowNodeOutputsItem(String key,
      Optional<RulebricksFlowNodeOutputsItemType> type, Optional<String> name,
      Map<String, Object> additionalProperties) {
    this.key = key;
    this.type = type;
    this.name = name;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("key")
  public String getKey() {
    return key;
  }

  @JsonProperty("type")
  public Optional<RulebricksFlowNodeOutputsItemType> getType() {
    return type;
  }

  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof RulebricksFlowNodeOutputsItem && equalTo((RulebricksFlowNodeOutputsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(RulebricksFlowNodeOutputsItem other) {
    return key.equals(other.key) && type.equals(other.type) && name.equals(other.name);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.key, this.type, this.name);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static KeyStage builder() {
    return new Builder();
  }

  public interface KeyStage {
    _FinalStage key(@NotNull String key);

    Builder from(RulebricksFlowNodeOutputsItem other);
  }

  public interface _FinalStage {
    RulebricksFlowNodeOutputsItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage type(Optional<RulebricksFlowNodeOutputsItemType> type);

    _FinalStage type(RulebricksFlowNodeOutputsItemType type);

    _FinalStage name(Optional<String> name);

    _FinalStage name(String name);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements KeyStage, _FinalStage {
    private String key;

    private Optional<String> name = Optional.empty();

    private Optional<RulebricksFlowNodeOutputsItemType> type = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(RulebricksFlowNodeOutputsItem other) {
      key(other.getKey());
      type(other.getType());
      name(other.getName());
      return this;
    }

    @java.lang.Override
    @JsonSetter("key")
    public _FinalStage key(@NotNull String key) {
      this.key = Objects.requireNonNull(key, "key must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public _FinalStage name(Optional<String> name) {
      this.name = name;
      return this;
    }

    @java.lang.Override
    public _FinalStage type(RulebricksFlowNodeOutputsItemType type) {
      this.type = Optional.ofNullable(type);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "type",
        nulls = Nulls.SKIP
    )
    public _FinalStage type(Optional<RulebricksFlowNodeOutputsItemType> type) {
      this.type = type;
      return this;
    }

    @java.lang.Override
    public RulebricksFlowNodeOutputsItem build() {
      return new RulebricksFlowNodeOutputsItem(key, type, name, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
