/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.rulebricks.core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = RulebricksFlowConnection.Builder.class
)
public final class RulebricksFlowConnection {
  private final String from;

  private final String to;

  private final Optional<String> output;

  private final Optional<String> input;

  private final Optional<Boolean> control;

  private final Map<String, Object> additionalProperties;

  private RulebricksFlowConnection(String from, String to, Optional<String> output,
      Optional<String> input, Optional<Boolean> control, Map<String, Object> additionalProperties) {
    this.from = from;
    this.to = to;
    this.output = output;
    this.input = input;
    this.control = control;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Source node ref.
   */
  @JsonProperty("from")
  public String getFrom() {
    return from;
  }

  /**
   * @return Target node ref.
   */
  @JsonProperty("to")
  public String getTo() {
    return to;
  }

  /**
   * @return (data) Source output key: a declared output of the source node, or - for a rule/origin source - one of the referenced rule's response field keys (an origin also exposes <code>request_&lt;field&gt;</code> passthroughs). Free-form; validated against the resolved rule at import time.
   */
  @JsonProperty("output")
  public Optional<String> getOutput() {
    return output;
  }

  /**
   * @return (data) Target input key. Required for rule/entity targets, where it must be one of the referenced rule's request field keys. Free-form; validated against the resolved rule at import time.
   */
  @JsonProperty("input")
  public Optional<String> getInput() {
    return input;
  }

  /**
   * @return Set true for a Continue If gating edge (carries no data).
   */
  @JsonProperty("control")
  public Optional<Boolean> getControl() {
    return control;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof RulebricksFlowConnection && equalTo((RulebricksFlowConnection) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(RulebricksFlowConnection other) {
    return from.equals(other.from) && to.equals(other.to) && output.equals(other.output) && input.equals(other.input) && control.equals(other.control);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.from, this.to, this.output, this.input, this.control);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static FromStage builder() {
    return new Builder();
  }

  public interface FromStage {
    /**
     * <p>Source node ref.</p>
     */
    ToStage from(@NotNull String from);

    Builder from(RulebricksFlowConnection other);
  }

  public interface ToStage {
    /**
     * <p>Target node ref.</p>
     */
    _FinalStage to(@NotNull String to);
  }

  public interface _FinalStage {
    RulebricksFlowConnection build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>(data) Source output key: a declared output of the source node, or - for a rule/origin source - one of the referenced rule's response field keys (an origin also exposes <code>request_&lt;field&gt;</code> passthroughs). Free-form; validated against the resolved rule at import time.</p>
     */
    _FinalStage output(Optional<String> output);

    _FinalStage output(String output);

    /**
     * <p>(data) Target input key. Required for rule/entity targets, where it must be one of the referenced rule's request field keys. Free-form; validated against the resolved rule at import time.</p>
     */
    _FinalStage input(Optional<String> input);

    _FinalStage input(String input);

    /**
     * <p>Set true for a Continue If gating edge (carries no data).</p>
     */
    _FinalStage control(Optional<Boolean> control);

    _FinalStage control(Boolean control);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements FromStage, ToStage, _FinalStage {
    private String from;

    private String to;

    private Optional<Boolean> control = Optional.empty();

    private Optional<String> input = Optional.empty();

    private Optional<String> output = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(RulebricksFlowConnection other) {
      from(other.getFrom());
      to(other.getTo());
      output(other.getOutput());
      input(other.getInput());
      control(other.getControl());
      return this;
    }

    /**
     * <p>Source node ref.</p>
     * <p>Source node ref.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("from")
    public ToStage from(@NotNull String from) {
      this.from = Objects.requireNonNull(from, "from must not be null");
      return this;
    }

    /**
     * <p>Target node ref.</p>
     * <p>Target node ref.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("to")
    public _FinalStage to(@NotNull String to) {
      this.to = Objects.requireNonNull(to, "to must not be null");
      return this;
    }

    /**
     * <p>Set true for a Continue If gating edge (carries no data).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage control(Boolean control) {
      this.control = Optional.ofNullable(control);
      return this;
    }

    /**
     * <p>Set true for a Continue If gating edge (carries no data).</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "control",
        nulls = Nulls.SKIP
    )
    public _FinalStage control(Optional<Boolean> control) {
      this.control = control;
      return this;
    }

    /**
     * <p>(data) Target input key. Required for rule/entity targets, where it must be one of the referenced rule's request field keys. Free-form; validated against the resolved rule at import time.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage input(String input) {
      this.input = Optional.ofNullable(input);
      return this;
    }

    /**
     * <p>(data) Target input key. Required for rule/entity targets, where it must be one of the referenced rule's request field keys. Free-form; validated against the resolved rule at import time.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "input",
        nulls = Nulls.SKIP
    )
    public _FinalStage input(Optional<String> input) {
      this.input = input;
      return this;
    }

    /**
     * <p>(data) Source output key: a declared output of the source node, or - for a rule/origin source - one of the referenced rule's response field keys (an origin also exposes <code>request_&lt;field&gt;</code> passthroughs). Free-form; validated against the resolved rule at import time.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage output(String output) {
      this.output = Optional.ofNullable(output);
      return this;
    }

    /**
     * <p>(data) Source output key: a declared output of the source node, or - for a rule/origin source - one of the referenced rule's response field keys (an origin also exposes <code>request_&lt;field&gt;</code> passthroughs). Free-form; validated against the resolved rule at import time.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "output",
        nulls = Nulls.SKIP
    )
    public _FinalStage output(Optional<String> output) {
      this.output = output;
      return this;
    }

    @java.lang.Override
    public RulebricksFlowConnection build() {
      return new RulebricksFlowConnection(from, to, output, input, control, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
