/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.rulebricks.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = RuleImportRequestCell.Builder.class
)
public final class RuleImportRequestCell {
  private final String op;

  private final List<Object> args;

  private final Map<String, Object> additionalProperties;

  private RuleImportRequestCell(String op, List<Object> args,
      Map<String, Object> additionalProperties) {
    this.op = op;
    this.args = args;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Operator name for this request comparison.
   */
  @JsonProperty("op")
  public String getOp() {
    return op;
  }

  /**
   * @return Operator arguments.
   */
  @JsonProperty("args")
  public List<Object> getArgs() {
    return args;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof RuleImportRequestCell && equalTo((RuleImportRequestCell) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(RuleImportRequestCell other) {
    return op.equals(other.op) && args.equals(other.args);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.op, this.args);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static OpStage builder() {
    return new Builder();
  }

  public interface OpStage {
    /**
     * <p>Operator name for this request comparison.</p>
     */
    _FinalStage op(@NotNull String op);

    Builder from(RuleImportRequestCell other);
  }

  public interface _FinalStage {
    RuleImportRequestCell build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Operator arguments.</p>
     */
    _FinalStage args(List<Object> args);

    _FinalStage addArgs(Object args);

    _FinalStage addAllArgs(List<Object> args);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements OpStage, _FinalStage {
    private String op;

    private List<Object> args = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(RuleImportRequestCell other) {
      op(other.getOp());
      args(other.getArgs());
      return this;
    }

    /**
     * <p>Operator name for this request comparison.</p>
     * <p>Operator name for this request comparison.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("op")
    public _FinalStage op(@NotNull String op) {
      this.op = Objects.requireNonNull(op, "op must not be null");
      return this;
    }

    /**
     * <p>Operator arguments.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllArgs(List<Object> args) {
      if (args != null) {
        this.args.addAll(args);
      }
      return this;
    }

    /**
     * <p>Operator arguments.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addArgs(Object args) {
      this.args.add(args);
      return this;
    }

    /**
     * <p>Operator arguments.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "args",
        nulls = Nulls.SKIP
    )
    public _FinalStage args(List<Object> args) {
      this.args.clear();
      if (args != null) {
        this.args.addAll(args);
      }
      return this;
    }

    @java.lang.Override
    public RuleImportRequestCell build() {
      return new RuleImportRequestCell(op, args, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
