/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class RunTestsResponseFailuresItemPolicy {
  public static final RunTestsResponseFailuresItemPolicy CONTAINS = new RunTestsResponseFailuresItemPolicy(Value.CONTAINS, "contains");

  public static final RunTestsResponseFailuresItemPolicy EXCLUDES = new RunTestsResponseFailuresItemPolicy(Value.EXCLUDES, "excludes");

  public static final RunTestsResponseFailuresItemPolicy MATCHES = new RunTestsResponseFailuresItemPolicy(Value.MATCHES, "matches");

  private final Value value;

  private final String string;

  RunTestsResponseFailuresItemPolicy(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof RunTestsResponseFailuresItemPolicy && this.string.equals(((RunTestsResponseFailuresItemPolicy) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case CONTAINS:
        return visitor.visitContains();
      case EXCLUDES:
        return visitor.visitExcludes();
      case MATCHES:
        return visitor.visitMatches();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static RunTestsResponseFailuresItemPolicy valueOf(String value) {
    switch (value) {
      case "contains":
        return CONTAINS;
      case "excludes":
        return EXCLUDES;
      case "matches":
        return MATCHES;
      default:
        return new RunTestsResponseFailuresItemPolicy(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    CONTAINS,

    MATCHES,

    EXCLUDES,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitContains();

    T visitMatches();

    T visitExcludes();

    T visitUnknown(String unknownType);
  }
}
