/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class SyncValuesResponseBlockedItemAction {
  public static final SyncValuesResponseBlockedItemAction ARCHIVED = new SyncValuesResponseBlockedItemAction(Value.ARCHIVED, "archived");

  private final Value value;

  private final String string;

  SyncValuesResponseBlockedItemAction(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof SyncValuesResponseBlockedItemAction && this.string.equals(((SyncValuesResponseBlockedItemAction) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case ARCHIVED:
        return visitor.visitArchived();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static SyncValuesResponseBlockedItemAction valueOf(String value) {
    switch (value) {
      case "archived":
        return ARCHIVED;
      default:
        return new SyncValuesResponseBlockedItemAction(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    ARCHIVED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitArchived();

    T visitUnknown(String unknownType);
  }
}
