/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.rulebricks.core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = UpsertObjectResponseValues.Builder.class
)
public final class UpsertObjectResponseValues {
  private final Optional<Integer> synced;

  private final Optional<Integer> archived;

  private final Optional<Integer> wouldSync;

  private final Optional<List<UpsertObjectResponseValuesWouldArchiveItem>> wouldArchive;

  private final Map<String, Object> additionalProperties;

  private UpsertObjectResponseValues(Optional<Integer> synced, Optional<Integer> archived,
      Optional<Integer> wouldSync,
      Optional<List<UpsertObjectResponseValuesWouldArchiveItem>> wouldArchive,
      Map<String, Object> additionalProperties) {
    this.synced = synced;
    this.archived = archived;
    this.wouldSync = wouldSync;
    this.wouldArchive = wouldArchive;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Managed values created or updated.
   */
  @JsonProperty("synced")
  public Optional<Integer> getSynced() {
    return synced;
  }

  /**
   * @return Previously generated values archived because the schema no longer declares them.
   */
  @JsonProperty("archived")
  public Optional<Integer> getArchived() {
    return archived;
  }

  /**
   * @return Dry run: managed values that would be synced.
   */
  @JsonProperty("would_sync")
  public Optional<Integer> getWouldSync() {
    return wouldSync;
  }

  /**
   * @return Dry run: values that would be archived.
   */
  @JsonProperty("would_archive")
  public Optional<List<UpsertObjectResponseValuesWouldArchiveItem>> getWouldArchive() {
    return wouldArchive;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof UpsertObjectResponseValues && equalTo((UpsertObjectResponseValues) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(UpsertObjectResponseValues other) {
    return synced.equals(other.synced) && archived.equals(other.archived) && wouldSync.equals(other.wouldSync) && wouldArchive.equals(other.wouldArchive);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.synced, this.archived, this.wouldSync, this.wouldArchive);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Integer> synced = Optional.empty();

    private Optional<Integer> archived = Optional.empty();

    private Optional<Integer> wouldSync = Optional.empty();

    private Optional<List<UpsertObjectResponseValuesWouldArchiveItem>> wouldArchive = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(UpsertObjectResponseValues other) {
      synced(other.getSynced());
      archived(other.getArchived());
      wouldSync(other.getWouldSync());
      wouldArchive(other.getWouldArchive());
      return this;
    }

    /**
     * <p>Managed values created or updated.</p>
     */
    @JsonSetter(
        value = "synced",
        nulls = Nulls.SKIP
    )
    public Builder synced(Optional<Integer> synced) {
      this.synced = synced;
      return this;
    }

    public Builder synced(Integer synced) {
      this.synced = Optional.ofNullable(synced);
      return this;
    }

    /**
     * <p>Previously generated values archived because the schema no longer declares them.</p>
     */
    @JsonSetter(
        value = "archived",
        nulls = Nulls.SKIP
    )
    public Builder archived(Optional<Integer> archived) {
      this.archived = archived;
      return this;
    }

    public Builder archived(Integer archived) {
      this.archived = Optional.ofNullable(archived);
      return this;
    }

    /**
     * <p>Dry run: managed values that would be synced.</p>
     */
    @JsonSetter(
        value = "would_sync",
        nulls = Nulls.SKIP
    )
    public Builder wouldSync(Optional<Integer> wouldSync) {
      this.wouldSync = wouldSync;
      return this;
    }

    public Builder wouldSync(Integer wouldSync) {
      this.wouldSync = Optional.ofNullable(wouldSync);
      return this;
    }

    /**
     * <p>Dry run: values that would be archived.</p>
     */
    @JsonSetter(
        value = "would_archive",
        nulls = Nulls.SKIP
    )
    public Builder wouldArchive(
        Optional<List<UpsertObjectResponseValuesWouldArchiveItem>> wouldArchive) {
      this.wouldArchive = wouldArchive;
      return this;
    }

    public Builder wouldArchive(List<UpsertObjectResponseValuesWouldArchiveItem> wouldArchive) {
      this.wouldArchive = Optional.ofNullable(wouldArchive);
      return this;
    }

    public UpsertObjectResponseValues build() {
      return new UpsertObjectResponseValues(synced, archived, wouldSync, wouldArchive, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
