/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.resources.infra;

import com.rulebricks.core.ClientOptions;
import com.rulebricks.core.RequestOptions;
import com.rulebricks.types.ScaleStatusResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncInfraClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawInfraClient rawClient;

  public AsyncInfraClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawInfraClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawInfraClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Reports the fleet scale-up state. Worker counts reflect solvers that have actually joined the processing group and can accept work. Self-hosted deployments only.
   */
  public CompletableFuture<ScaleStatusResponse> status() {
    return this.rawClient.status().thenApply(response -> response.body());
  }

  /**
   * Reports the fleet scale-up state. Worker counts reflect solvers that have actually joined the processing group and can accept work. Self-hosted deployments only.
   */
  public CompletableFuture<ScaleStatusResponse> status(RequestOptions requestOptions) {
    return this.rawClient.status(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Pre-scales the deployment's solver fleet to its maximum capacity ahead of a large batch workload, so the first wave of requests never pays the scale-from-baseline window. Takes no request body: the target is always the deployment's own configured ceiling. The fleet stays warm for a bounded window (default 10 minutes; repeat calls refresh it), after which normal autoscaling reclaims the capacity - an unused warm-up costs at most that window. Poll the GET variant until <code>status</code> is <code>ready</code> before starting the batch. Self-hosted deployments only.
   */
  public CompletableFuture<ScaleStatusResponse> scale() {
    return this.rawClient.scale().thenApply(response -> response.body());
  }

  /**
   * Pre-scales the deployment's solver fleet to its maximum capacity ahead of a large batch workload, so the first wave of requests never pays the scale-from-baseline window. Takes no request body: the target is always the deployment's own configured ceiling. The fleet stays warm for a bounded window (default 10 minutes; repeat calls refresh it), after which normal autoscaling reclaims the capacity - an unused warm-up costs at most that window. Poll the GET variant until <code>status</code> is <code>ready</code> before starting the batch. Self-hosted deployments only.
   */
  public CompletableFuture<ScaleStatusResponse> scale(RequestOptions requestOptions) {
    return this.rawClient.scale(requestOptions).thenApply(response -> response.body());
  }
}
