/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.errors;

import com.rulebricks.core.RulebricksApiApiException;
import java.lang.Object;
import okhttp3.Response;

public final class InternalServerError extends RulebricksApiApiException {
  /**
   * The body of the response that triggered the exception.
   */
  private final Object body;

  public InternalServerError(Object body) {
    super("InternalServerError", 500, body);
    this.body = body;
  }

  public InternalServerError(Object body, Response rawResponse) {
    super("InternalServerError", 500, body, rawResponse);
    this.body = body;
  }

  /**
   * @return the body
   */
  @java.lang.Override
  public Object body() {
    return this.body;
  }
}
