/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.resources.flows;

import com.rulebricks.core.ClientOptions;
import com.rulebricks.core.RequestOptions;
import com.rulebricks.resources.flows.requests.ExecuteFlowsRequest;
import java.lang.Object;
import java.lang.String;
import java.util.Map;

public class FlowsClient {
  protected final ClientOptions clientOptions;

  private final RawFlowsClient rawClient;

  public FlowsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawFlowsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawFlowsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Execute a flow by its slug. Optionally target a specific published version (e.g. <code>3</code>) or a release environment (e.g. <code>production</code>) via the <code>version</code> path segment; <code>latest</code> (the default) executes the current published version.
   */
  public Map<String, Object> execute(String slug, String version, ExecuteFlowsRequest request) {
    return this.rawClient.execute(slug, version, request).body();
  }

  /**
   * Execute a flow by its slug. Optionally target a specific published version (e.g. <code>3</code>) or a release environment (e.g. <code>production</code>) via the <code>version</code> path segment; <code>latest</code> (the default) executes the current published version.
   */
  public Map<String, Object> execute(String slug, String version, ExecuteFlowsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.execute(slug, version, request, requestOptions).body();
  }
}
