/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.errors;

import com.rulebricks.core.RulebricksApiApiException;
import com.rulebricks.types.ContextOperationError;
import okhttp3.Response;

public final class ContentTooLargeError extends RulebricksApiApiException {
  /**
   * The body of the response that triggered the exception.
   */
  private final ContextOperationError body;

  public ContentTooLargeError(ContextOperationError body) {
    super("ContentTooLargeError", 413, body);
    this.body = body;
  }

  public ContentTooLargeError(ContextOperationError body, Response rawResponse) {
    super("ContentTooLargeError", 413, body, rawResponse);
    this.body = body;
  }

  /**
   * @return the body
   */
  @java.lang.Override
  public ContextOperationError body() {
    return this.body;
  }
}
