/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ContextInstancePendingEvaluationType {
  public static final ContextInstancePendingEvaluationType RULE = new ContextInstancePendingEvaluationType(Value.RULE, "rule");

  public static final ContextInstancePendingEvaluationType FLOW = new ContextInstancePendingEvaluationType(Value.FLOW, "flow");

  private final Value value;

  private final String string;

  ContextInstancePendingEvaluationType(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ContextInstancePendingEvaluationType && this.string.equals(((ContextInstancePendingEvaluationType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case RULE:
        return visitor.visitRule();
      case FLOW:
        return visitor.visitFlow();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ContextInstancePendingEvaluationType valueOf(String value) {
    switch (value) {
      case "rule":
        return RULE;
      case "flow":
        return FLOW;
      default:
        return new ContextInstancePendingEvaluationType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    RULE,

    FLOW,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitRule();

    T visitFlow();

    T visitUnknown(String unknownType);
  }
}
