/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.rulebricks.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ExportManifestPreviewResponsePreview.Builder.class
)
public final class ExportManifestPreviewResponsePreview {
  private final Optional<ExportManifestPreviewResponsePreviewCounts> counts;

  private final Optional<ExportManifestPreviewResponsePreviewItems> items;

  private final Map<String, Object> additionalProperties;

  private ExportManifestPreviewResponsePreview(
      Optional<ExportManifestPreviewResponsePreviewCounts> counts,
      Optional<ExportManifestPreviewResponsePreviewItems> items,
      Map<String, Object> additionalProperties) {
    this.counts = counts;
    this.items = items;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("counts")
  public Optional<ExportManifestPreviewResponsePreviewCounts> getCounts() {
    return counts;
  }

  @JsonProperty("items")
  public Optional<ExportManifestPreviewResponsePreviewItems> getItems() {
    return items;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ExportManifestPreviewResponsePreview && equalTo((ExportManifestPreviewResponsePreview) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ExportManifestPreviewResponsePreview other) {
    return counts.equals(other.counts) && items.equals(other.items);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.counts, this.items);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<ExportManifestPreviewResponsePreviewCounts> counts = Optional.empty();

    private Optional<ExportManifestPreviewResponsePreviewItems> items = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ExportManifestPreviewResponsePreview other) {
      counts(other.getCounts());
      items(other.getItems());
      return this;
    }

    @JsonSetter(
        value = "counts",
        nulls = Nulls.SKIP
    )
    public Builder counts(Optional<ExportManifestPreviewResponsePreviewCounts> counts) {
      this.counts = counts;
      return this;
    }

    public Builder counts(ExportManifestPreviewResponsePreviewCounts counts) {
      this.counts = Optional.ofNullable(counts);
      return this;
    }

    @JsonSetter(
        value = "items",
        nulls = Nulls.SKIP
    )
    public Builder items(Optional<ExportManifestPreviewResponsePreviewItems> items) {
      this.items = items;
      return this;
    }

    public Builder items(ExportManifestPreviewResponsePreviewItems items) {
      this.items = Optional.ofNullable(items);
      return this;
    }

    public ExportManifestPreviewResponsePreview build() {
      return new ExportManifestPreviewResponsePreview(counts, items, additionalProperties);
    }
  }
}
