/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.rulebricks.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = RuleImportConditionRow.Builder.class
)
public final class RuleImportConditionRow {
  private final Map<String, RuleImportRequestCell> request;

  private final Map<String, RuleImportResponseCell> response;

  private final RuleImportRowSettings settings;

  private final Map<String, Object> additionalProperties;

  private RuleImportConditionRow(Map<String, RuleImportRequestCell> request,
      Map<String, RuleImportResponseCell> response, RuleImportRowSettings settings,
      Map<String, Object> additionalProperties) {
    this.request = request;
    this.response = response;
    this.settings = settings;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Request-side cells keyed by request schema field key.
   */
  @JsonProperty("request")
  public Map<String, RuleImportRequestCell> getRequest() {
    return request;
  }

  /**
   * @return Response-side cells keyed by response schema field key.
   */
  @JsonProperty("response")
  public Map<String, RuleImportResponseCell> getResponse() {
    return response;
  }

  @JsonProperty("settings")
  public RuleImportRowSettings getSettings() {
    return settings;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof RuleImportConditionRow && equalTo((RuleImportConditionRow) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(RuleImportConditionRow other) {
    return request.equals(other.request) && response.equals(other.response) && settings.equals(other.settings);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.request, this.response, this.settings);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static SettingsStage builder() {
    return new Builder();
  }

  public interface SettingsStage {
    _FinalStage settings(@NotNull RuleImportRowSettings settings);

    Builder from(RuleImportConditionRow other);
  }

  public interface _FinalStage {
    RuleImportConditionRow build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Request-side cells keyed by request schema field key.</p>
     */
    _FinalStage request(Map<String, RuleImportRequestCell> request);

    _FinalStage putAllRequest(Map<String, RuleImportRequestCell> request);

    _FinalStage request(String key, RuleImportRequestCell value);

    /**
     * <p>Response-side cells keyed by response schema field key.</p>
     */
    _FinalStage response(Map<String, RuleImportResponseCell> response);

    _FinalStage putAllResponse(Map<String, RuleImportResponseCell> response);

    _FinalStage response(String key, RuleImportResponseCell value);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements SettingsStage, _FinalStage {
    private RuleImportRowSettings settings;

    private Map<String, RuleImportResponseCell> response = new LinkedHashMap<>();

    private Map<String, RuleImportRequestCell> request = new LinkedHashMap<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(RuleImportConditionRow other) {
      request(other.getRequest());
      response(other.getResponse());
      settings(other.getSettings());
      return this;
    }

    @java.lang.Override
    @JsonSetter("settings")
    public _FinalStage settings(@NotNull RuleImportRowSettings settings) {
      this.settings = Objects.requireNonNull(settings, "settings must not be null");
      return this;
    }

    /**
     * <p>Response-side cells keyed by response schema field key.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage response(String key, RuleImportResponseCell value) {
      this.response.put(key, value);
      return this;
    }

    /**
     * <p>Response-side cells keyed by response schema field key.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage putAllResponse(Map<String, RuleImportResponseCell> response) {
      if (response != null) {
        this.response.putAll(response);
      }
      return this;
    }

    /**
     * <p>Response-side cells keyed by response schema field key.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "response",
        nulls = Nulls.SKIP
    )
    public _FinalStage response(Map<String, RuleImportResponseCell> response) {
      this.response.clear();
      if (response != null) {
        this.response.putAll(response);
      }
      return this;
    }

    /**
     * <p>Request-side cells keyed by request schema field key.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage request(String key, RuleImportRequestCell value) {
      this.request.put(key, value);
      return this;
    }

    /**
     * <p>Request-side cells keyed by request schema field key.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage putAllRequest(Map<String, RuleImportRequestCell> request) {
      if (request != null) {
        this.request.putAll(request);
      }
      return this;
    }

    /**
     * <p>Request-side cells keyed by request schema field key.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "request",
        nulls = Nulls.SKIP
    )
    public _FinalStage request(Map<String, RuleImportRequestCell> request) {
      this.request.clear();
      if (request != null) {
        this.request.putAll(request);
      }
      return this;
    }

    @java.lang.Override
    public RuleImportConditionRow build() {
      return new RuleImportConditionRow(request, response, settings, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
