/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.resources.assets.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ExportManifestRequestRootType {
  public static final ExportManifestRequestRootType RULE = new ExportManifestRequestRootType(Value.RULE, "rule");

  public static final ExportManifestRequestRootType CONTEXT = new ExportManifestRequestRootType(Value.CONTEXT, "context");

  public static final ExportManifestRequestRootType VALUE = new ExportManifestRequestRootType(Value.VALUE, "value");

  public static final ExportManifestRequestRootType FLOW = new ExportManifestRequestRootType(Value.FLOW, "flow");

  private final Value value;

  private final String string;

  ExportManifestRequestRootType(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ExportManifestRequestRootType && this.string.equals(((ExportManifestRequestRootType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case RULE:
        return visitor.visitRule();
      case CONTEXT:
        return visitor.visitContext();
      case VALUE:
        return visitor.visitValue();
      case FLOW:
        return visitor.visitFlow();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ExportManifestRequestRootType valueOf(String value) {
    switch (value) {
      case "rule":
        return RULE;
      case "context":
        return CONTEXT;
      case "value":
        return VALUE;
      case "flow":
        return FLOW;
      default:
        return new ExportManifestRequestRootType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    RULE,

    FLOW,

    CONTEXT,

    VALUE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitRule();

    T visitFlow();

    T visitContext();

    T visitValue();

    T visitUnknown(String unknownType);
  }
}
