/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.resources.assets.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.rulebricks.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ImportManifestRequestLegacyRuleMappingValue.Builder.class
)
public final class ImportManifestRequestLegacyRuleMappingValue {
  private final Optional<ImportManifestRequestLegacyRuleMappingValueAction> action;

  private final Optional<String> ruleId;

  private final Map<String, Object> additionalProperties;

  private ImportManifestRequestLegacyRuleMappingValue(
      Optional<ImportManifestRequestLegacyRuleMappingValueAction> action, Optional<String> ruleId,
      Map<String, Object> additionalProperties) {
    this.action = action;
    this.ruleId = ruleId;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("action")
  public Optional<ImportManifestRequestLegacyRuleMappingValueAction> getAction() {
    return action;
  }

  @JsonProperty("rule_id")
  public Optional<String> getRuleId() {
    return ruleId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ImportManifestRequestLegacyRuleMappingValue && equalTo((ImportManifestRequestLegacyRuleMappingValue) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ImportManifestRequestLegacyRuleMappingValue other) {
    return action.equals(other.action) && ruleId.equals(other.ruleId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.action, this.ruleId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<ImportManifestRequestLegacyRuleMappingValueAction> action = Optional.empty();

    private Optional<String> ruleId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ImportManifestRequestLegacyRuleMappingValue other) {
      action(other.getAction());
      ruleId(other.getRuleId());
      return this;
    }

    @JsonSetter(
        value = "action",
        nulls = Nulls.SKIP
    )
    public Builder action(Optional<ImportManifestRequestLegacyRuleMappingValueAction> action) {
      this.action = action;
      return this;
    }

    public Builder action(ImportManifestRequestLegacyRuleMappingValueAction action) {
      this.action = Optional.ofNullable(action);
      return this;
    }

    @JsonSetter(
        value = "rule_id",
        nulls = Nulls.SKIP
    )
    public Builder ruleId(Optional<String> ruleId) {
      this.ruleId = ruleId;
      return this;
    }

    public Builder ruleId(String ruleId) {
      this.ruleId = Optional.ofNullable(ruleId);
      return this;
    }

    public ImportManifestRequestLegacyRuleMappingValue build() {
      return new ImportManifestRequestLegacyRuleMappingValue(action, ruleId, additionalProperties);
    }
  }
}
