/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.resources.objects;

import com.rulebricks.core.ClientOptions;
import com.rulebricks.core.RequestOptions;
import com.rulebricks.resources.objects.requests.DeleteObjectsRequest;
import com.rulebricks.resources.objects.requests.GetObjectsRequest;
import com.rulebricks.types.DeleteObjectResponse;
import com.rulebricks.types.UpsertObjectRequest;
import com.rulebricks.types.UpsertObjectResponse;
import com.rulebricks.types.WorkspaceObject;
import java.lang.String;
import java.util.List;
import java.util.concurrent.CompletableFuture;

public class AsyncObjectsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawObjectsClient rawClient;

  public AsyncObjectsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawObjectsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawObjectsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Lists the workspace's objects (JSON Schemas). The provided API key must have permission to view vocabulary values. Results are scoped to the API key holder's user groups.
   */
  public CompletableFuture<List<WorkspaceObject>> list() {
    return this.rawClient.list().thenApply(response -> response.body());
  }

  /**
   * Lists the workspace's objects (JSON Schemas). The provided API key must have permission to view vocabulary values. Results are scoped to the API key holder's user groups.
   */
  public CompletableFuture<List<WorkspaceObject>> list(RequestOptions requestOptions) {
    return this.rawClient.list(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Creates or updates an object by ID or name and syncs enum values it generates. <code>content</code> and at least one of <code>id</code> or <code>name</code> are required. Objects help workspace admins programmatically determine multiple collections of values based on Rulebricks' contracts with external systems from a single JSON Schema source. Renaming the object's display name does not move its managed collection paths: those paths derive from schema field keys. When a schema field key itself is renamed, <code>field_rename</code> can preserve the generated values' identities.
   */
  public CompletableFuture<UpsertObjectResponse> upsert(UpsertObjectRequest request) {
    return this.rawClient.upsert(request).thenApply(response -> response.body());
  }

  /**
   * Creates or updates an object by ID or name and syncs enum values it generates. <code>content</code> and at least one of <code>id</code> or <code>name</code> are required. Objects help workspace admins programmatically determine multiple collections of values based on Rulebricks' contracts with external systems from a single JSON Schema source. Renaming the object's display name does not move its managed collection paths: those paths derive from schema field keys. When a schema field key itself is renamed, <code>field_rename</code> can preserve the generated values' identities.
   */
  public CompletableFuture<UpsertObjectResponse> upsert(UpsertObjectRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.upsert(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Fetches one object by ID or exact name. The provided API key must have permission to view vocabulary values.
   */
  public CompletableFuture<WorkspaceObject> get(String objectId) {
    return this.rawClient.get(objectId).thenApply(response -> response.body());
  }

  /**
   * Fetches one object by ID or exact name. The provided API key must have permission to view vocabulary values.
   */
  public CompletableFuture<WorkspaceObject> get(String objectId, RequestOptions requestOptions) {
    return this.rawClient.get(objectId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Fetches one object by ID or exact name. The provided API key must have permission to view vocabulary values.
   */
  public CompletableFuture<WorkspaceObject> get(String objectId, GetObjectsRequest request) {
    return this.rawClient.get(objectId, request).thenApply(response -> response.body());
  }

  /**
   * Fetches one object by ID or exact name. The provided API key must have permission to view vocabulary values.
   */
  public CompletableFuture<WorkspaceObject> get(String objectId, GetObjectsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.get(objectId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Deletes the object. By default, unused values are permanently deleted while values referenced by draft, current, or historical rules, flows, or other vocabulary values are archived. Pass values=detach to keep every generated value active as an ordinary, hand-editable value.
   */
  public CompletableFuture<DeleteObjectResponse> delete(String objectId) {
    return this.rawClient.delete(objectId).thenApply(response -> response.body());
  }

  /**
   * Deletes the object. By default, unused values are permanently deleted while values referenced by draft, current, or historical rules, flows, or other vocabulary values are archived. Pass values=detach to keep every generated value active as an ordinary, hand-editable value.
   */
  public CompletableFuture<DeleteObjectResponse> delete(String objectId,
      RequestOptions requestOptions) {
    return this.rawClient.delete(objectId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Deletes the object. By default, unused values are permanently deleted while values referenced by draft, current, or historical rules, flows, or other vocabulary values are archived. Pass values=detach to keep every generated value active as an ordinary, hand-editable value.
   */
  public CompletableFuture<DeleteObjectResponse> delete(String objectId,
      DeleteObjectsRequest request) {
    return this.rawClient.delete(objectId, request).thenApply(response -> response.body());
  }

  /**
   * Deletes the object. By default, unused values are permanently deleted while values referenced by draft, current, or historical rules, flows, or other vocabulary values are archived. Pass values=detach to keep every generated value active as an ordinary, hand-editable value.
   */
  public CompletableFuture<DeleteObjectResponse> delete(String objectId,
      DeleteObjectsRequest request, RequestOptions requestOptions) {
    return this.rawClient.delete(objectId, request, requestOptions).thenApply(response -> response.body());
  }
}
