/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.resources.assets.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ImportManifestRequestConflictStrategy {
  public static final ImportManifestRequestConflictStrategy UPDATE = new ImportManifestRequestConflictStrategy(Value.UPDATE, "update");

  public static final ImportManifestRequestConflictStrategy ERROR = new ImportManifestRequestConflictStrategy(Value.ERROR, "error");

  public static final ImportManifestRequestConflictStrategy SKIP = new ImportManifestRequestConflictStrategy(Value.SKIP, "skip");

  private final Value value;

  private final String string;

  ImportManifestRequestConflictStrategy(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ImportManifestRequestConflictStrategy && this.string.equals(((ImportManifestRequestConflictStrategy) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case UPDATE:
        return visitor.visitUpdate();
      case ERROR:
        return visitor.visitError();
      case SKIP:
        return visitor.visitSkip();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ImportManifestRequestConflictStrategy valueOf(String value) {
    switch (value) {
      case "update":
        return UPDATE;
      case "error":
        return ERROR;
      case "skip":
        return SKIP;
      default:
        return new ImportManifestRequestConflictStrategy(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    UPDATE,

    SKIP,

    ERROR,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitUpdate();

    T visitSkip();

    T visitError();

    T visitUnknown(String unknownType);
  }
}
