/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.resources.assets.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.rulebricks.core.ObjectMappers;
import com.rulebricks.types.ManifestLabeledAsset;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ImportManifestRequestManifest.Builder.class
)
public final class ImportManifestRequestManifest {
  private final Optional<String> version;

  private final Optional<List<ManifestLabeledAsset>> rules;

  private final Optional<List<ManifestLabeledAsset>> flows;

  private final Optional<List<Map<String, Object>>> entities;

  private final Optional<List<Map<String, Object>>> contexts;

  private final Optional<List<Map<String, Object>>> values;

  private final Map<String, Object> additionalProperties;

  private ImportManifestRequestManifest(Optional<String> version,
      Optional<List<ManifestLabeledAsset>> rules, Optional<List<ManifestLabeledAsset>> flows,
      Optional<List<Map<String, Object>>> entities, Optional<List<Map<String, Object>>> contexts,
      Optional<List<Map<String, Object>>> values, Map<String, Object> additionalProperties) {
    this.version = version;
    this.rules = rules;
    this.flows = flows;
    this.entities = entities;
    this.contexts = contexts;
    this.values = values;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Manifest format version.
   */
  @JsonProperty("version")
  public Optional<String> getVersion() {
    return version;
  }

  /**
   * @return Rules to import.
   */
  @JsonProperty("rules")
  public Optional<List<ManifestLabeledAsset>> getRules() {
    return rules;
  }

  /**
   * @return Flows to import.
   */
  @JsonProperty("flows")
  public Optional<List<ManifestLabeledAsset>> getFlows() {
    return flows;
  }

  /**
   * @return Contexts to import.
   */
  @JsonProperty("entities")
  public Optional<List<Map<String, Object>>> getEntities() {
    return entities;
  }

  /**
   * @return Alias for <code>entities</code>, accepted so manifests produced by the export endpoint (which names this array <code>contexts</code>) can be imported without modification. Ignored when <code>entities</code> is present and non-empty.
   */
  @JsonProperty("contexts")
  public Optional<List<Map<String, Object>>> getContexts() {
    return contexts;
  }

  /**
   * @return Vocabulary values to import. Entries in object-managed namespaces are skipped and reported instead of being overwritten.
   */
  @JsonProperty("values")
  public Optional<List<Map<String, Object>>> getValues() {
    return values;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ImportManifestRequestManifest && equalTo((ImportManifestRequestManifest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ImportManifestRequestManifest other) {
    return version.equals(other.version) && rules.equals(other.rules) && flows.equals(other.flows) && entities.equals(other.entities) && contexts.equals(other.contexts) && values.equals(other.values);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.version, this.rules, this.flows, this.entities, this.contexts, this.values);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> version = Optional.empty();

    private Optional<List<ManifestLabeledAsset>> rules = Optional.empty();

    private Optional<List<ManifestLabeledAsset>> flows = Optional.empty();

    private Optional<List<Map<String, Object>>> entities = Optional.empty();

    private Optional<List<Map<String, Object>>> contexts = Optional.empty();

    private Optional<List<Map<String, Object>>> values = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ImportManifestRequestManifest other) {
      version(other.getVersion());
      rules(other.getRules());
      flows(other.getFlows());
      entities(other.getEntities());
      contexts(other.getContexts());
      values(other.getValues());
      return this;
    }

    /**
     * <p>Manifest format version.</p>
     */
    @JsonSetter(
        value = "version",
        nulls = Nulls.SKIP
    )
    public Builder version(Optional<String> version) {
      this.version = version;
      return this;
    }

    public Builder version(String version) {
      this.version = Optional.ofNullable(version);
      return this;
    }

    /**
     * <p>Rules to import.</p>
     */
    @JsonSetter(
        value = "rules",
        nulls = Nulls.SKIP
    )
    public Builder rules(Optional<List<ManifestLabeledAsset>> rules) {
      this.rules = rules;
      return this;
    }

    public Builder rules(List<ManifestLabeledAsset> rules) {
      this.rules = Optional.ofNullable(rules);
      return this;
    }

    /**
     * <p>Flows to import.</p>
     */
    @JsonSetter(
        value = "flows",
        nulls = Nulls.SKIP
    )
    public Builder flows(Optional<List<ManifestLabeledAsset>> flows) {
      this.flows = flows;
      return this;
    }

    public Builder flows(List<ManifestLabeledAsset> flows) {
      this.flows = Optional.ofNullable(flows);
      return this;
    }

    /**
     * <p>Contexts to import.</p>
     */
    @JsonSetter(
        value = "entities",
        nulls = Nulls.SKIP
    )
    public Builder entities(Optional<List<Map<String, Object>>> entities) {
      this.entities = entities;
      return this;
    }

    public Builder entities(List<Map<String, Object>> entities) {
      this.entities = Optional.ofNullable(entities);
      return this;
    }

    /**
     * <p>Alias for <code>entities</code>, accepted so manifests produced by the export endpoint (which names this array <code>contexts</code>) can be imported without modification. Ignored when <code>entities</code> is present and non-empty.</p>
     */
    @JsonSetter(
        value = "contexts",
        nulls = Nulls.SKIP
    )
    public Builder contexts(Optional<List<Map<String, Object>>> contexts) {
      this.contexts = contexts;
      return this;
    }

    public Builder contexts(List<Map<String, Object>> contexts) {
      this.contexts = Optional.ofNullable(contexts);
      return this;
    }

    /**
     * <p>Vocabulary values to import. Entries in object-managed namespaces are skipped and reported instead of being overwritten.</p>
     */
    @JsonSetter(
        value = "values",
        nulls = Nulls.SKIP
    )
    public Builder values(Optional<List<Map<String, Object>>> values) {
      this.values = values;
      return this;
    }

    public Builder values(List<Map<String, Object>> values) {
      this.values = Optional.ofNullable(values);
      return this;
    }

    public ImportManifestRequestManifest build() {
      return new ImportManifestRequestManifest(version, rules, flows, entities, contexts, values, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
