/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.rulebricks.resources.objects.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class DeleteObjectsRequestValues {
  public static final DeleteObjectsRequestValues ARCHIVE = new DeleteObjectsRequestValues(Value.ARCHIVE, "archive");

  public static final DeleteObjectsRequestValues DETACH = new DeleteObjectsRequestValues(Value.DETACH, "detach");

  private final Value value;

  private final String string;

  DeleteObjectsRequestValues(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof DeleteObjectsRequestValues && this.string.equals(((DeleteObjectsRequestValues) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case ARCHIVE:
        return visitor.visitArchive();
      case DETACH:
        return visitor.visitDetach();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static DeleteObjectsRequestValues valueOf(String value) {
    switch (value) {
      case "archive":
        return ARCHIVE;
      case "detach":
        return DETACH;
      default:
        return new DeleteObjectsRequestValues(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    ARCHIVE,

    DETACH,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitArchive();

    T visitDetach();

    T visitUnknown(String unknownType);
  }
}
